# Generated by Django 4.1.6 on 2023-02-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productos',
            name='En_Almacen',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Vendidos',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
