# Generated by Django 4.1.7 on 2023-02-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movement',
            name='type',
            field=models.CharField(choices=[('EP', 'Entrada de Productos'), ('CP', 'Creado Producto'), ('SP', 'Salida de Productos'), ('SD', 'Salida de Dinero'), ('eP', 'Editado de Producto'), ('VP', 'Venta de Productos'), ('rP', 'Reembolso de Productos'), ('RP', 'Remover Producto')], max_length=2),
        ),
    ]
