# Generated by Django 4.1.7 on 2023-02-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0005_remove_movement_refund_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='type',
            field=models.CharField(choices=[('EP', 'Entrada de Productos'), ('CP', 'Creado Producto'), ('SP', 'Salida de Productos'), ('RD', 'Retirada de Dinero'), ('eP', 'Editado de Producto'), ('VP', 'Venta de Productos'), ('rP', 'Reembolso de Productos'), ('RP', 'Remover Producto')], max_length=2),
        ),
    ]
