# Generated by Django 4.1.6 on 2023-02-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0005_alter_productos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinero', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='tipo',
            field=models.CharField(choices=[('EP', 'Entrada_Productos'), ('SP', 'Salida_Productos'), ('SD', 'Salida_Dinero')], max_length=2),
        ),
    ]
