# Generated by Django 4.1.7 on 2023-02-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0006_alter_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='no_imagen.jpg', null=True, upload_to='productos'),
        ),
    ]
