# Generated by Django 4.1.6 on 2023-02-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0007_movimientos_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, default='no_imagen.jpg', null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(max_length=6),
        ),
    ]
