# Generated by Django 4.1.7 on 2023-02-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0008_alter_movement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='date1',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
