# Generated by Django 4.1.6 on 2023-02-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0008_alter_productos_imagen_alter_productos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, default='productos/no_imagen.jpg', null=True, upload_to='productos'),
        ),
    ]
