# Generated by Django 4.1.6 on 2023-02-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0009_alter_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
