# Generated by Django 4.1.6 on 2023-02-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0010_productos_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='tipo',
            field=models.CharField(choices=[('EP', 'Entrada Productos'), ('SP', 'Salida Productos'), ('SD', 'Salida Dinero'), ('VP', 'Venta Productos')], max_length=2),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
