# Generated by Django 4.1.7 on 2023-02-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0010_remove_movement_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RN_product', to='AlmacenApp.product'),
        ),
    ]
