# Generated by Django 4.1.6 on 2023-02-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0011_alter_movimientos_tipo_alter_productos_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='id',
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='importe',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
