# Generated by Django 4.1.7 on 2023-02-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0012_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='type',
            field=models.CharField(choices=[('EP', 'Agregado de Productos'), ('CP', 'Creado de Producto'), ('SP', 'Quitado de Productos'), ('RD', 'Retiro de Dinero'), ('eP', 'Editado de Producto'), ('VP', 'Venta de Productos'), ('rP', 'Reembolso de Productos'), ('RP', 'Removido de Producto'), ('AC', 'Agregado de Categoria'), ('RC', 'Removido de Categoria')], max_length=2),
        ),
    ]
