# Generated by Django 4.1.7 on 2023-02-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0013_alter_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='extra_info',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
