# Generated by Django 4.1.7 on 2023-02-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0013_alter_productos_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_fecha', models.DateField(auto_now_add=True)),
                ('_cantidad', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MPEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_fecha', models.DateField(auto_now_add=True)),
                ('_cantidad', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MPSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_fecha', models.DateField(auto_now_add=True)),
                ('_cantidad', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MPVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_fecha', models.DateField(auto_now_add=True)),
                ('_cantidad', models.IntegerField(default=0)),
                ('_importe', models.IntegerField(default=0)),
                ('_precio_vigente', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nombre', models.CharField(max_length=30, unique=True)),
                ('_precio', models.IntegerField()),
                ('_imagen', models.ImageField(blank=True, default='productos/no_imagen.jpg', null=True, unique=True, upload_to='productos')),
                ('_almacenado', models.IntegerField(blank=True, default=0)),
                ('_vendido', models.IntegerField(blank=True, default=0)),
                ('_descripcion', models.CharField(blank=True, max_length=100)),
                ('_eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Caja',
            new_name='CajaRegistradora',
        ),
        migrations.RenameField(
            model_name='cajaregistradora',
            old_name='dinero',
            new_name='_dinero',
        ),
        migrations.CreateModel(
            name='MPReembolso',
            fields=[
                ('mpventa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AlmacenApp.mpventa')),
            ],
            options={
                'abstract': False,
            },
            bases=('AlmacenApp.mpventa',),
        ),
        migrations.DeleteModel(
            name='Movimientos',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.AddField(
            model_name='mpventa',
            name='_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlmacenApp.producto'),
        ),
        migrations.AddField(
            model_name='mpsalida',
            name='_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlmacenApp.producto'),
        ),
        migrations.AddField(
            model_name='mpentrada',
            name='_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlmacenApp.producto'),
        ),
        migrations.AddField(
            model_name='mpreembolso',
            name='_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reembolso', to='AlmacenApp.mpventa'),
        ),
    ]
