# Generated by Django 4.1.7 on 2023-02-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0014_mdsalida_mpentrada_mpsalida_mpventa_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cajaregistradora',
            old_name='_dinero',
            new_name='dinero',
        ),
    ]
