# Generated by Django 4.1.7 on 2023-02-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0015_rename__dinero_cajaregistradora_dinero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mdsalida',
            old_name='_cantidad',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='mdsalida',
            old_name='_fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='mpentrada',
            old_name='_cantidad',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='mpentrada',
            old_name='_fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='mpentrada',
            old_name='_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='mpreembolso',
            old_name='_movimiento',
            new_name='movimiento',
        ),
        migrations.RenameField(
            model_name='mpsalida',
            old_name='_cantidad',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='mpsalida',
            old_name='_fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='mpsalida',
            old_name='_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='mpventa',
            old_name='_cantidad',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='mpventa',
            old_name='_fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='mpventa',
            old_name='_importe',
            new_name='importe',
        ),
        migrations.RenameField(
            model_name='mpventa',
            old_name='_precio_vigente',
            new_name='precio_vigente',
        ),
        migrations.RenameField(
            model_name='mpventa',
            old_name='_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='_almacenado',
            new_name='almacenado',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='_descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='_eliminado',
            new_name='eliminado',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='_imagen',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='_nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='_precio',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='_vendido',
            new_name='vendido',
        ),
    ]
