# Generated by Django 4.1.7 on 2023-02-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlmacenApp', '0016_rename__cantidad_mdsalida_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EP', 'Entrada de Productos'), ('SP', 'Salida de Productos'), ('SD', 'Salida de Dinero'), ('VP', 'Venta de Productos'), ('RD', 'Reembolso de Productos')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lot', models.IntegerField(default=0)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('refund_id', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='productos/no_imagen.jpg', null=True, upload_to='productos')),
                ('stored', models.IntegerField(blank=True, default=0)),
                ('sold', models.IntegerField(blank=True, default=0)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='CajaRegistradora',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='movement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlmacenApp.product'),
        ),
    ]
