# Generated by Django 4.1.7 on 2023-04-15 18:37

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('unit_stored', models.IntegerField(default=0)),
                ('pair_stored', models.IntegerField(default=0)),
                ('unit_sold', models.IntegerField(default=0)),
                ('pair_sold', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('pair', models.BooleanField(default=False)),
                ('unit_price', models.IntegerField(default=0)),
                ('unit_profit_worker', models.IntegerField(default=0)),
                ('pair_price', models.IntegerField(blank=True, default=0, null=True)),
                ('pair_profit_worker', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, default='no_imagen.jpg', null=True, upload_to='productos')),
                ('unit_stored', models.IntegerField(blank=True, default=0)),
                ('pair_stored', models.IntegerField(blank=True, default=0)),
                ('unit_sold', models.IntegerField(blank=True, default=0)),
                ('pair_sold', models.IntegerField(blank=True, default=0)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('removed', models.BooleanField(default=False)),
                ('confirm', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UsEr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_worker', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('money', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CP', 'Creado de Producto'), ('eP', 'Editado de Producto'), ('RP', 'Removido de Producto'), ('EP', 'Agregado de Productos'), ('cP', 'Confirmado de Producto'), ('VP', 'Venta de Productos'), ('rP', 'Reembolso de Productos'), ('SP', 'Quitado de Productos'), ('AC', 'Agregado de Categoría'), ('RC', 'Removido de Categoría'), ('AD', 'Agregado de Dinero'), ('RD', 'Retiro de Dinero')], max_length=2)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('lot', models.IntegerField(default=0)),
                ('extra_info_str', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_info_int', models.IntegerField(default=0)),
                ('extra_info_int_1', models.IntegerField(default=0)),
                ('extra_info_bool', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StickersApp.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='StickersApp.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StickersApp.product'),
        ),
    ]
