# Generated by Django 4.1.7 on 2023-04-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StickersApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='category',
        ),
        migrations.AlterField(
            model_name='movement',
            name='extra_info_bool',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='type',
            field=models.CharField(choices=[('CP', 'Creado de Producto'), ('eP', 'Editado de Producto'), ('RP', 'Removido de Producto'), ('EP', 'Agregado de Productos'), ('cP', 'Confirmado de Producto'), ('nC', 'No Confirmado de Producto'), ('VP', 'Venta de Productos'), ('rP', 'Reembolso de Productos'), ('SP', 'Quitado de Productos'), ('AD', 'Agregado de Dinero'), ('RD', 'Retiro de Dinero')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
