# Generated by Django 4.1.7 on 2023-04-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StickersApp', '0002_remove_movement_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='extra_info_bool',
            field=models.BooleanField(default=False),
        ),
    ]
