# Generated by Django 4.1.7 on 2023-04-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StickersApp', '0003_alter_movement_extra_info_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pair_profit_worker',
        ),
        migrations.AddField(
            model_name='product',
            name='pair_profit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_profit',
            field=models.IntegerField(default=0),
        ),
    ]
