# Generated by Django 4.1.7 on 2023-04-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StickersApp', '0004_remove_product_pair_profit_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pair_profit_worker',
            field=models.IntegerField(default=0),
        ),
    ]
